var admTimeTracking=Math.floor((new Date).getTime()/1E3),_ADMFlashDetect=new function(){var a,d,b,f,h,c=this;c.installed=!1;c.raw="";c.major=-1;c.minor=-1;c.revision=-1;c.revisionStr="";var e=[{name:"ShockwaveFlash.ShockwaveFlash.7",version:function(a){return j(a)}},{name:"ShockwaveFlash.ShockwaveFlash.6",version:function(a){var b="6.0.r21";try{a.AllowScriptAccess="always",b=j(a)}catch(c){}return b}},{name:"ShockwaveFlash.ShockwaveFlash",version:function(a){return j(a)}}],j=function(a){var b=-1;try{b=
a.GetVariable("$version")}catch(c){}return b};c.majorAtLeast=function(a){return c.major>=a};c.minorAtLeast=function(a){return c.minor>=a};c.revisionAtLeast=function(a){return c.revision>=a};c.versionAtLeast=function(a){var b=[c.major,c.minor,c.revision],d=Math.min(b.length,arguments.length);for(i=0;i<d;i++)if(b[i]>=arguments[i]){if(!(i+1<d&&b[i]==arguments[i]))return!0}else return!1};if(navigator.plugins&&0<navigator.plugins.length){if((e=navigator.mimeTypes)&&e["application/x-shockwave-flash"]&&
e["application/x-shockwave-flash"].enabledPlugin&&e["application/x-shockwave-flash"].enabledPlugin.description){var g=e["application/x-shockwave-flash"].enabledPlugin.description,k=g,e=k.split(/ +/),g=e[2].split(/\./),e=e[3];a=k;d=parseInt(g[0],10);b=parseInt(g[1],10);f=e;h=parseInt(e.replace(/[a-zA-Z]/g,""),10)||c.revision;c.raw=a;c.major=d;c.minor=b;c.revisionStr=f;c.revision=h;c.installed=!0}}else if(-1==navigator.appVersion.indexOf("Mac")&&window.execScript){g=-1;for(k=0;k<e.length&&-1==g;k++){a=
-1;try{a=new ActiveXObject(e[k].name)}catch(l){a={activeXError:!0}}a.activeXError||(c.installed=!0,g=e[k].version(a),-1!=g&&(a=g,f=a.split(","),d=parseInt(f[0].split(" ")[1],10),b=parseInt(f[1],10),h=parseInt(f[2],10),f=f[2],c.raw=a.replace("Shockwave Flash ",""),c.major=d,c.minor=b,c.revision=h,c.revisionStr=f))}}c._ADMFlashDetect=void 0};
function admcrc32(a){function d(a,b){for(var c=0;b;)c=2*c+a%2,a/=2,a-=a%1,b--;return c}a=String(a);var b=2>arguments.length?79764919:arguments[1],f=4>arguments.length?4294967295:arguments[3],h=3>arguments.length?4294967295:arguments[2],c=[],e,j,g;for(e=255;0<=e;e--){g=d(e,32);for(j=0;8>j;j++)g=(2*g^(g>>>31)%2*b)>>>0;c[e]=d(g,32)}for(e=0;e<a.length;e++){g=a.charCodeAt(e);if(255<g)throw new RangeError;j=h%256^g;h=(h/256^c[j])>>>0}return(h^f)>>>0}
var paramBrowser1={screen_Resolution:screen.width+""+screen.height,screen_Color:screen.colorDepth,hostname:document.domain.replace("www.",""),cookieEnabled:navigator.cookieEnabled?1:0,javaEnabled:navigator.javaEnabled()?1:0,referrer:document.referrer,url:function(){var a=top.location+"",d=this.hostname;return""==d?a:a.substring(a.indexOf(d)+d.length,a.length)},domainRef:function(){var a=document.referrer;if(""==a)return"";var d=a.indexOf("//"),b=a.indexOf("/",d+2);return a.substring(d+2,b)},flashVersion:function(){return _ADMFlashDetect.major+
"."+_ADMFlashDetect.minor+"."+_ADMFlashDetect.revisionStr},zenURL:{encode:function(a){if(-1!=document.domain.indexOf("muachung.vn")&&-1==a.indexOf("http://")){for(var d="undefined"==typeof ADS_CHECKER?"":ADS_CHECKER.getCookie("mc_city"),b="/ha-noi /tp-ho-chi-minh /da-nang /nha-trang /vung-tau /hai-phong".split(" "),f="/Ha-Noi /TP-HCM /Da-Nang /Khanh-Hoa /Ba-Ria-Vung-Tau /Hai-Phong".split(" "),h=0;h<b.length;h++)if(0==a.indexOf(b[h]))return a=a.replace(b[h],f[h]),encodeURIComponent(a);b={22:"/Ha-Noi",
29:"/TP-HCM",15:"/Da-Nang",68:"/Khanh-Hoa",26:"/Hai-Phong",67:"/Ba-Ria-Vung-Tau"};""!=d&&"undefined"!=typeof b[d]&&(a=b[d]+a)}return encodeURIComponent(a)},decode:function(a){return decodeURIComponent(a.replace(/\+/g," "))}},getQuery:function(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");a=RegExp("[\\?&]"+a+"=([^&#]*)").exec(document.URL);return null==a?"":decodeURIComponent(a[1].replace(/\+/g," "))},setCookie:function(a,d,b,f,h,c){(new Date).getTime();f=""==f?"/":f;b=0==b||""==b?(new Date(+new Date+
864E5)).toGMTString():(new Date(+new Date+6E4*b)).toGMTString();a=[a+"="+escape(d)];for(var e in b={expires:b,path:f,domain:h})b[e]&&a.push(e+"="+b[e]);return c&&a.push("secure"),document.cookie=a.join(";"),!0},getCookie:function(a){return 0<document.cookie.length&&(c_start=document.cookie.indexOf(a+"="),-1!=c_start)?(c_start=c_start+a.length+1,c_end=document.cookie.indexOf(";",c_start),-1==c_end&&(c_end=document.cookie.length),unescape(document.cookie.substring(c_start,c_end))):""},crSessId:function(){var a=
this.getCookie("_admSid");a.split("|");""==a&&(a=Math.floor(1E10*Math.random()),this.setCookie("_admSid",a,20,"/"))},upSessId:function(){this.getCookie("_admSid");var a=Math.floor(1E10*Math.random());this.setCookie("_admSid",a,20,"/")},getSessId:function(){var a=this.getCookie("_admSid");if(""!=a&&!isNaN(parseInt(a)))return parseInt(a);a=Math.floor(1E10*Math.random());this.setCookie("_admSid",a,20,"/");return a}};paramBrowser1.crSessId();
var _ADMBrowser={Version:function(){var a=999;-1!=navigator.appVersion.indexOf("MSIE")&&(a=parseFloat(navigator.appVersion.split("MSIE")[1]));return a}},_admBrV=_ADMBrowser.Version(),admTrackingchk=!1;
function loadpageView(){if(!1===admTrackingchk){var a="http://azlog.vn/pv.gif?",d=document.URL,b="0",f=d.indexOf("?");-1!=f&&(d=d.substring(0,f));if(d=d.match(/([\d]+).htm/g))b=d[0].replace(".htm",""),15<=b.length&&(b=b.substring(8,b.length));a+=paramBrowser1.flashVersion()+";";a+=paramBrowser1.javaEnabled+";";a+=paramBrowser1.screen_Resolution+";";a+=paramBrowser1.screen_Color+";";d=Math.floor((new Date).getTime()/1E3);a+=d-admTimeTracking+";";a+=admcrc32(paramBrowser1.url())+";";a+=paramBrowser1.hostname+
";";a+=paramBrowser1.domainRef()+";";a+=paramBrowser1.zenURL.encode(paramBrowser1.url())+";";a+=paramBrowser1.getSessId()+";";a+=encodeURIComponent(document.referrer)+";";a+=(""==b?0:b)+";"+("undefined"==typeof admParamSite?"0":admParamSite);(new Image).src=a}admTrackingchk=!0}function admTkpv(a,d,b){"addEventListener"in a?a.addEventListener(d,b):"attachEvent"in a&&a.attachEvent("on"+d,b)}
"beforeunload"in window||"onbeforeunload"in window?-1!=navigator.userAgent.indexOf("Firefox")?admTkpv(window,"unload",loadpageView):admTkpv(window,"beforeunload",loadpageView):loadpageView();