jQuery.fn.extend({selectbox:function(i){return this.each(function(){new jQuery.SelectBox(this,i)})}});if(!window.console)var console={log:function(){}};
jQuery.SelectBox=function(i,r){function l(){k=0;d.hide()}function n(j){var c=jQuery("li",d);if(!c||0==c.length)return!1;for(firstchoice=0;$(c[firstchoice]).hasClass(a.groupClass);)firstchoice++;e+=j;$(c[e]).hasClass(a.groupClass)&&(e+=j);e<firstchoice?a.loopnoStep?e=c.size()-1:e=c.size():a.loopnoStep&&e>c.size()-1?e=firstchoice:e>c.size()&&(e=firstchoice);var b=jQuery(c[e]).get(0),j=d.get(0);b.offsetTop+b.offsetHeight>j.scrollTop+j.clientHeight?j.scrollTop=b.offsetTop+b.offsetHeight-j.clientHeight:
b.offsetTop<j.scrollTop&&(j.scrollTop=b.offsetTop);c.removeClass(a.hoverClass);jQuery(c[e]).addClass(a.hoverClass)}function p(){var b=jQuery("li."+a.currentClass,d).get(0),c=(""+b.id).split("_"),c=c[c.length-1];a.onChangeCallback?(f.get(0).selectedIndex=$("li",d).index(b),a.onChangeParams={selectedVal:f.val()},a.onChangeCallback(a.onChangeParams)):(f.val(c),f.change());"span"==a.inputType?g.html($(b).html()):g.val($(b).html());return!0}var a=r||{};a.inputType=a.inputType||"input";a.inputClass=a.inputClass||
"selectbox";a.containerClass=a.containerClass||"selectbox-wrapper";a.hoverClass=a.hoverClass||"current";a.currentClass=a.currentClass||"selected";a.groupClass=a.groupClass||"groupname";a.maxHeight=a.maxHeight||200;a.loopnoStep=a.loopnoStep||!1;a.onChangeCallback=a.onChangeCallback||!1;a.onChangeParams=a.onChangeParams||!1;a.debug=a.debug||!1;var h=i.id,e=0,q=!1,k=0,f=jQuery(i),d,m=a,b=document.createElement("div");d=jQuery(b);d.attr("id",h+"_container");d.addClass(m.containerClass);d.css("display",
"none");var g,m=a;"span"==a.inputType?(b=document.createElement("span"),b=jQuery(b),b.attr("id",h+"_input"),b.addClass(m.inputClass),b.attr("tabIndex",f.attr("tabindex"))):(b=document.createElement("input"),b=jQuery(b),b.attr("id",h+"_input"),b.attr("type","text"),b.addClass(m.inputClass),b.attr("autocomplete","off"),b.attr("readonly","readonly"),b.attr("tabIndex",f.attr("tabindex")),b.css("width",f.css("width")));g=b;f.hide().before(g).before(d);d.append(function(b){var c=[],e=document.createElement("ul"),
c=f.children("option");if(0==c.length){var h=[],h=f.children("optgroup");for(x=0;x<h.length;x++){var c=$("#"+h[x].id).children("option"),i=document.createElement("li");i.setAttribute("id",b+"_"+$(this).val());i.innerHTML=$("#"+h[x].id).attr("label");i.className=a.groupClass;e.appendChild(i);c.each(function(){var c=document.createElement("li");c.setAttribute("id",b+"_"+$(this).val());c.innerHTML=$(this).html();$(this).is(":selected")&&(g.html($(this).html()),$(c).addClass(a.currentClass));e.appendChild(c);
$(c).mouseover(function(b){k=1;a.debug&&console.log("over on : "+this.id);jQuery(b.target,d).addClass(a.hoverClass)}).mouseout(function(b){k=-1;a.debug&&console.log("out on : "+this.id);jQuery(b.target,d).removeClass(a.hoverClass)}).click(function(){$("li."+a.hoverClass,d).get(0);a.debug&&console.log("click on :"+this.id);$("li."+a.currentClass,d).removeClass(a.currentClass);$(this).addClass(a.currentClass);p();f.get(0).blur();l()})})}}else c.each(function(){var c=document.createElement("li");c.setAttribute("id",
b+"_"+$(this).val());c.innerHTML=$(this).html();$(this).is(":selected")&&(g.val($(this).html()),$(c).addClass(a.currentClass));e.appendChild(c);$(c).mouseover(function(b){k=1;a.debug&&console.log("over on : "+this.id);jQuery(b.target,d).addClass(a.hoverClass)}).mouseout(function(b){k=-1;a.debug&&console.log("out on : "+this.id);jQuery(b.target,d).removeClass(a.hoverClass)}).click(function(){$("li."+a.hoverClass,d).get(0);a.debug&&console.log("click on :"+this.id);$("li."+a.currentClass,d).removeClass(a.currentClass);
$(this).addClass(a.currentClass);p();f.get(0).blur();l()})});return e}(g.attr("id"))).hide();h=g.css("width");d.height()>a.maxHeight?(d.width(parseInt(h)+parseInt(g.css("paddingRight"))+parseInt(g.css("paddingLeft"))),d.height(a.maxHeight)):d.width(h);g.click(function(){q||d.toggle()}).focus(function(){d.not(":visible")&&(q=!0,d.show())}).keydown(function(b){switch(b.keyCode){case 38:b.preventDefault();n(-1);break;case 40:b.preventDefault();n(1);break;case 13:b.preventDefault();$("li."+a.hoverClass).trigger("click");
break;case 27:l()}}).blur(function(){d.is(":visible")&&0<k?a.debug&&console.log("container visible and has focus"):jQuery.browser.msie&&8>jQuery.browser.version.substr(0,1)||jQuery.browser.safari?-1==document.activeElement.getAttribute("id").indexOf("_container")?l():g.focus():l()})};
