function nv_login_info(b){nv_ajax("get",nv_siteroot+"index.php?"+nv_lang_variable+"="+nv_sitelang+"&"+nv_name_variable+"=banners&"+nv_fc_variable+"=logininfo&num="+nv_randomPassword(8),"",b);return!1}
function nv_cl_login_submit(b,d,h,g,c,i,e,j,k,l){var f=nv_fc_variable+"=logininfo&save=1",e=document.getElementById(e);if(e.value.length>b||e.value.length<d||!nv_namecheck.test(e.value))return c=nv_error_login.replace(/\[max\]/g,b),c=c.replace(/\[min\]/g,d),alert(c),e.focus(),!1;f+="&login="+e.value;d=document.getElementById(j);if(d.value.length>h||d.value.length<g||!nv_namecheck.test(d.value))return c=nv_error_password.replace(/\[max\]/g,h),c=c.replace(/\[min\]/g,g),alert(c),d.focus(),!1;f+="&password="+
d.value;if(i){g=document.getElementById(k);if(g.value.length!=c)return c=nv_error_seccode.replace(/\[num\]/g,c),alert(c),g.focus(),!1;f+="&seccode="+g.value}nv_settimeout_disable(l,5E3);nv_ajax("post",nv_siteroot+"index.php?"+nv_lang_variable+"="+nv_sitelang+"&"+nv_name_variable+"=banners",f+"&num="+nv_randomPassword(8),"","nv_cl_login_submit_res");return!1}
function nv_cl_login_submit_res(b){if("OK"==b)return window.location.href=window.location.href,!1;alert(nv_login_failed);nv_login_info(b);return!1}function nv_cl_info(b){nv_ajax("get",nv_siteroot+"index.php?"+nv_lang_variable+"="+nv_sitelang+"&"+nv_name_variable+"=banners&"+nv_fc_variable+"=clinfo&num="+nv_randomPassword(8),"",b);return!1}
function nv_cl_edit(b){nv_ajax("get",nv_siteroot+"index.php?"+nv_lang_variable+"="+nv_sitelang+"&"+nv_name_variable+"=banners&"+nv_fc_variable+"=cledit&num="+nv_randomPassword(8),"",b);return!1}
function nv_cl_edit_save(b,d,h,g,c,i,e,j,k,l,f){var a=nv_fc_variable+"=cledit&save=1",a=a+("&full_name="+rawurlencode(strip_tags(trim(document.getElementById(b).value.replace(/[\s]{2,}/g," "))))),a=a+("&email="+rawurlencode(strip_tags(document.getElementById(d).value.replace(/[^a-zA-Z0-9\_\-\.\@]/g,"")))),a=a+("&website="+rawurlencode(strip_tags(trim(document.getElementById(h).value.replace(/[^a-zA-Z0-9\:\#\!\:\.\?\+\=\&\%\@\-\/\,]/g,""))))),a=a+("&location="+rawurlencode(strip_tags(trim(document.getElementById(g).value.replace(/[\s]{2,}/g,
" "))))),a=a+("&yim="+rawurlencode(strip_tags(trim(document.getElementById(c).value.replace(/[^a-zA-Z0-9\.\-\_]/g,""))))),a=a+("&phone="+rawurlencode(strip_tags(trim(document.getElementById(i).value.replace(/[^0-9\.\+\-\#\(\) ]/g,"").replace(/[\s]{2,}/g," "))))),a=a+("&fax="+rawurlencode(strip_tags(trim(document.getElementById(e).value.replace(/[^0-9\.\+\-\#\(\) ]/g,"").replace(/[\s]{2,}/g," "))))),a=a+("&mobile="+rawurlencode(strip_tags(trim(document.getElementById(j).value.replace(/[^0-9\.\+\-\#\(\) ]/g,
"").replace(/[\s]{2,}/g," "))))),a=a+("&pass="+rawurlencode(strip_tags(trim(document.getElementById(k).value)))),a=a+("&re_pass="+rawurlencode(strip_tags(trim(document.getElementById(l).value)))),a=a+("&num="+nv_randomPassword(8));nv_settimeout_disable(f,5E3);nv_ajax("post",nv_siteroot+"index.php?"+nv_lang_variable+"="+nv_sitelang+"&"+nv_name_variable+"=banners",a,"","nv_cl_edit_save_res");return!1}
function nv_cl_edit_save_res(b){b=b.split("|");if("OK"==b[0])nv_cl_info(b[1]);else{var d=b[0].replace(/\&[l|r]dquo\;/g,"");alert(d);b[1]&&document.getElementById(b[1]).focus()}return!1};
